// Generated by gencpp from file icim_robot/ICIM_action.msg
// DO NOT EDIT!


#ifndef ICIM_ROBOT_MESSAGE_ICIM_ACTION_H
#define ICIM_ROBOT_MESSAGE_ICIM_ACTION_H

#include <ros/service_traits.h>


#include <icim_robot/ICIM_actionRequest.h>
#include <icim_robot/ICIM_actionResponse.h>


namespace icim_robot
{

struct ICIM_action
{

typedef ICIM_actionRequest Request;
typedef ICIM_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ICIM_action
} // namespace icim_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icim_robot::ICIM_action > {
  static const char* value()
  {
    return "ac222bde2a288d489953362d931be211";
  }

  static const char* value(const ::icim_robot::ICIM_action&) { return value(); }
};

template<>
struct DataType< ::icim_robot::ICIM_action > {
  static const char* value()
  {
    return "icim_robot/ICIM_action";
  }

  static const char* value(const ::icim_robot::ICIM_action&) { return value(); }
};


// service_traits::MD5Sum< ::icim_robot::ICIM_actionRequest> should match
// service_traits::MD5Sum< ::icim_robot::ICIM_action >
template<>
struct MD5Sum< ::icim_robot::ICIM_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icim_robot::ICIM_action >::value();
  }
  static const char* value(const ::icim_robot::ICIM_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icim_robot::ICIM_actionRequest> should match
// service_traits::DataType< ::icim_robot::ICIM_action >
template<>
struct DataType< ::icim_robot::ICIM_actionRequest>
{
  static const char* value()
  {
    return DataType< ::icim_robot::ICIM_action >::value();
  }
  static const char* value(const ::icim_robot::ICIM_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icim_robot::ICIM_actionResponse> should match
// service_traits::MD5Sum< ::icim_robot::ICIM_action >
template<>
struct MD5Sum< ::icim_robot::ICIM_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icim_robot::ICIM_action >::value();
  }
  static const char* value(const ::icim_robot::ICIM_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icim_robot::ICIM_actionResponse> should match
// service_traits::DataType< ::icim_robot::ICIM_action >
template<>
struct DataType< ::icim_robot::ICIM_actionResponse>
{
  static const char* value()
  {
    return DataType< ::icim_robot::ICIM_action >::value();
  }
  static const char* value(const ::icim_robot::ICIM_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICIM_ROBOT_MESSAGE_ICIM_ACTION_H
