<?xml version="1.0" encoding="utf-8"?>
<robot name="conveyor" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="conveyor" params="depth width height mass">
        <link name="anchor" />
        <joint name="fixed" type="fixed">
            <parent link="anchor" />
            <child link="frame" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>
        
        <link name="frame">
            <inertial>
                <origin xyz="0 0 ${​​​​​height/2}​​​​​" rpy="0 0 0" />
                <mass value="${​​​​​mass}​​​​​" />
                <inertia ixx="${​​​​​(mass*(height**2 + depth**2))/12}​​​​​" ixy="0" ixz="0"
                iyy="${​​​​​(mass*(width**2 + depth**2))/12}​​​​​" iyz="0"
                izz="${​​​​​(mass*(width**2 + height**2))/12}​​​​​" />
            </inertial>
            <visual>
                <origin xyz="0 0 ${​​​​​height/2}​​​​​" rpy="0 0 0" />
                <geometry>
                    <box size="${​​​​​width}​​​​​ ${​​​​​depth}​​​​​ ${​​​​​height}​​​​​" />
                </geometry>
                <material name="grey">
                    <color rgba="0.5 0.5 0.5 1" />
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 ${​​​​​height/2}​​​​​" rpy="0 0 0" />
                <geometry>
                    <box size="${​​​​​width}​​​​​ ${​​​​​depth}​​​​​ ${​​​​​height}​​​​​" />
                </geometry>
            </collision>
        </link>
        
        <joint name="frame_belt" type="prismatic">
            <origin xyz="0 0 ${​​​​​height}​​​​​" rpy="0 0 0" />
            <parent link="frame" />
            <child link="belt" />
            <axis xyz="0 1 0" />
            <!-- <limit lower="0" upper="0.01" effort="1000" velocity="1000" /> -->
            <limit lower="0" upper="1" effort="1000" velocity="1000" />
        </joint>

        <link name="belt">
            <inertial>
                <origin xyz="0 0 ${​​​​​height}​​​​​" rpy="0 0 0" />
                <mass value="${​​​​​mass}​​​​​" />
                <inertia ixx="${​​​​​(mass*(height**2 + depth**2))/12}​​​​​" ixy="0" ixz="0"
                iyy="${​​​​​(mass*(width**2 + depth**2))/12}​​​​​" iyz="0"
                izz="${​​​​​(mass*(width**2 + height**2))/12}​​​​​" />
            </inertial>
            <visual>
                <origin xyz="0 0 0.001" rpy="0 0 0" />
                <geometry>
                    <box size="${​​​​​width}​​​​​ ${​​​​​depth}​​​​​ 0.001" />
                </geometry>
                <material name="belt">
                    <color rgba="1 0 1 1" />
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0.001" rpy="0 0 0" />
                <geometry>
                    <box size="${​​​​​width}​​​​​ ${​​​​​depth}​​​​​ 0.001" />
                </geometry>
            </collision>
        </link>
        
        <gazebo>
            <plugin name="conveyor_belt_plugin" filename="libROSConveyorBeltPlugin.so">
                <robot_namespace>/</robot_namespace>
                <link>belt</link>
                <joint>frame_belt</joint>
                <power>0</power>
                <max_velocity>1.0</max_velocity>
            </plugin>
        </gazebo>
        
        <gazebo reference="frame">
            <material>Gazebo/Grey</material>
        </gazebo>
        
        <gazebo reference="belt">
            <material>Gazebo/FlatBlack</material>
        </gazebo>
        
        </xacro:macro><xacro:arg name="depth" default="1.2" />
        <xacro:arg name="width" default="0.5" />
        <xacro:arg name="height" default="0.3" />
        
        <xacro:conveyor depth="$(arg depth)" width="$(arg width)" 
        height="$(arg height)" mass="1000" />
    </robot>