// Generated by gencpp from file elfin_robot_msgs/ElfinIODRead.msg
// DO NOT EDIT!


#ifndef ELFIN_ROBOT_MSGS_MESSAGE_ELFINIODREAD_H
#define ELFIN_ROBOT_MSGS_MESSAGE_ELFINIODREAD_H

#include <ros/service_traits.h>


#include <elfin_robot_msgs/ElfinIODReadRequest.h>
#include <elfin_robot_msgs/ElfinIODReadResponse.h>


namespace elfin_robot_msgs
{

struct ElfinIODRead
{

typedef ElfinIODReadRequest Request;
typedef ElfinIODReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ElfinIODRead
} // namespace elfin_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::elfin_robot_msgs::ElfinIODRead > {
  static const char* value()
  {
    return "17d1458f56860abf97b7dcd22dda435a";
  }

  static const char* value(const ::elfin_robot_msgs::ElfinIODRead&) { return value(); }
};

template<>
struct DataType< ::elfin_robot_msgs::ElfinIODRead > {
  static const char* value()
  {
    return "elfin_robot_msgs/ElfinIODRead";
  }

  static const char* value(const ::elfin_robot_msgs::ElfinIODRead&) { return value(); }
};


// service_traits::MD5Sum< ::elfin_robot_msgs::ElfinIODReadRequest> should match
// service_traits::MD5Sum< ::elfin_robot_msgs::ElfinIODRead >
template<>
struct MD5Sum< ::elfin_robot_msgs::ElfinIODReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::elfin_robot_msgs::ElfinIODRead >::value();
  }
  static const char* value(const ::elfin_robot_msgs::ElfinIODReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::elfin_robot_msgs::ElfinIODReadRequest> should match
// service_traits::DataType< ::elfin_robot_msgs::ElfinIODRead >
template<>
struct DataType< ::elfin_robot_msgs::ElfinIODReadRequest>
{
  static const char* value()
  {
    return DataType< ::elfin_robot_msgs::ElfinIODRead >::value();
  }
  static const char* value(const ::elfin_robot_msgs::ElfinIODReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::elfin_robot_msgs::ElfinIODReadResponse> should match
// service_traits::MD5Sum< ::elfin_robot_msgs::ElfinIODRead >
template<>
struct MD5Sum< ::elfin_robot_msgs::ElfinIODReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::elfin_robot_msgs::ElfinIODRead >::value();
  }
  static const char* value(const ::elfin_robot_msgs::ElfinIODReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::elfin_robot_msgs::ElfinIODReadResponse> should match
// service_traits::DataType< ::elfin_robot_msgs::ElfinIODRead >
template<>
struct DataType< ::elfin_robot_msgs::ElfinIODReadResponse>
{
  static const char* value()
  {
    return DataType< ::elfin_robot_msgs::ElfinIODRead >::value();
  }
  static const char* value(const ::elfin_robot_msgs::ElfinIODReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ELFIN_ROBOT_MSGS_MESSAGE_ELFINIODREAD_H
