// Generated by gencpp from file elfin_robot_msgs/ElfinIODReadRequest.msg
// DO NOT EDIT!


#ifndef ELFIN_ROBOT_MSGS_MESSAGE_ELFINIODREADREQUEST_H
#define ELFIN_ROBOT_MSGS_MESSAGE_ELFINIODREADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace elfin_robot_msgs
{
template <class ContainerAllocator>
struct ElfinIODReadRequest_
{
  typedef ElfinIODReadRequest_<ContainerAllocator> Type;

  ElfinIODReadRequest_()
    : data(false)  {
    }
  ElfinIODReadRequest_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ElfinIODReadRequest_

typedef ::elfin_robot_msgs::ElfinIODReadRequest_<std::allocator<void> > ElfinIODReadRequest;

typedef boost::shared_ptr< ::elfin_robot_msgs::ElfinIODReadRequest > ElfinIODReadRequestPtr;
typedef boost::shared_ptr< ::elfin_robot_msgs::ElfinIODReadRequest const> ElfinIODReadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator1> & lhs, const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator1> & lhs, const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace elfin_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "elfin_robot_msgs/ElfinIODReadRequest";
  }

  static const char* value(const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n"
;
  }

  static const char* value(const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ElfinIODReadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::elfin_robot_msgs::ElfinIODReadRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ELFIN_ROBOT_MSGS_MESSAGE_ELFINIODREADREQUEST_H
