// Generated by gencpp from file elfin_robot_msgs/SetFloat64.msg
// DO NOT EDIT!


#ifndef ELFIN_ROBOT_MSGS_MESSAGE_SETFLOAT64_H
#define ELFIN_ROBOT_MSGS_MESSAGE_SETFLOAT64_H

#include <ros/service_traits.h>


#include <elfin_robot_msgs/SetFloat64Request.h>
#include <elfin_robot_msgs/SetFloat64Response.h>


namespace elfin_robot_msgs
{

struct SetFloat64
{

typedef SetFloat64Request Request;
typedef SetFloat64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64
} // namespace elfin_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::elfin_robot_msgs::SetFloat64 > {
  static const char* value()
  {
    return "3f47c51e9da05852f0d7f484f9279955";
  }

  static const char* value(const ::elfin_robot_msgs::SetFloat64&) { return value(); }
};

template<>
struct DataType< ::elfin_robot_msgs::SetFloat64 > {
  static const char* value()
  {
    return "elfin_robot_msgs/SetFloat64";
  }

  static const char* value(const ::elfin_robot_msgs::SetFloat64&) { return value(); }
};


// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64Request> should match
// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64 >
template<>
struct MD5Sum< ::elfin_robot_msgs::SetFloat64Request>
{
  static const char* value()
  {
    return MD5Sum< ::elfin_robot_msgs::SetFloat64 >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::elfin_robot_msgs::SetFloat64Request> should match
// service_traits::DataType< ::elfin_robot_msgs::SetFloat64 >
template<>
struct DataType< ::elfin_robot_msgs::SetFloat64Request>
{
  static const char* value()
  {
    return DataType< ::elfin_robot_msgs::SetFloat64 >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64Response> should match
// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64 >
template<>
struct MD5Sum< ::elfin_robot_msgs::SetFloat64Response>
{
  static const char* value()
  {
    return MD5Sum< ::elfin_robot_msgs::SetFloat64 >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::elfin_robot_msgs::SetFloat64Response> should match
// service_traits::DataType< ::elfin_robot_msgs::SetFloat64 >
template<>
struct DataType< ::elfin_robot_msgs::SetFloat64Response>
{
  static const char* value()
  {
    return DataType< ::elfin_robot_msgs::SetFloat64 >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ELFIN_ROBOT_MSGS_MESSAGE_SETFLOAT64_H
