controller_list:
  - name: fake_elfin_arm_controller
    type: $(arg execution_type)
    joints:
      - elfin_joint1
      - elfin_joint2
      - elfin_joint3
      - elfin_joint4
      - elfin_joint5
      - elfin_joint6
  - name: fake_robotiq_gripper_controller
    type: $(arg execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses.
  - group: elfin_arm
    pose: pre_pickup
  - group: robotiq_gripper
    pose: open