# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: elfin_arm
  joint_model_group_pose: pre_pickup
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - elfin_joint1
    - elfin_joint2
    - elfin_joint3
    - elfin_joint4
    - elfin_joint5
    - elfin_joint6
    - finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: elfin_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - elfin_joint1
      - elfin_joint2
      - elfin_joint3
      - elfin_joint4
      - elfin_joint5
      - elfin_joint6
  - name: robotiq_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - finger_joint
elfin_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - elfin_joint1
    - elfin_joint2
    - elfin_joint3
    - elfin_joint4
    - elfin_joint5
    - elfin_joint6
  gains:
    elfin_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elfin_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elfin_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elfin_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elfin_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elfin_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
robotiq_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - finger_joint
  gains:
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1